name: Deploy React App to GitHub Pages

on:
  push:
    branches: ["main"] 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    # This instructs GitHub to run all npm commands inside your './(root)'' folder
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install 

      - name: Build Project
        run: npm run build

      # This points to the compiled folder inside your 'app' directory
      # IMPORTANT: If using Create React App instead of Vite, change '/dist' to '/build'
      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: './StatdecUK_app/build' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
